-- Initial SystemSafetyConfig Seed Data
-- Free Plan Configuration

INSERT INTO shadowguard."SystemSafetyConfigs" (
    "Id",
    "ElevenLabsPlanTier",
    "MonthlyPrice",
    "MonthlyCredits",
    "CreditsUsed",
    "EstimatedMinutes",
    "MinutesUsed",
    "AbsoluteMaxConcurrentConnections",
    "AbsoluteMaxVoiceSlots",
    "AbsoluteMaxConversationMinutes",
    "AbsoluteMaxDailyMinutesPerUser",
    "AbsoluteMaxDailyCredits",
    "CreditWarningThreshold",
    "CreditDangerThreshold",
    "EnableHardLimits",
    "EnableAutoStop",
    "EnableDailyLimits",
    "AlertEmail",
    "AlertPhone",
    "SlackWebhookUrl",
    "PeriodStartDate",
    "PeriodEndDate",
    "AutoRenew",
    "IsActive",
    "CreatedAt",
    "IsDeleted"
)
VALUES (
    gen_random_uuid(),
    'Free',
    0,
    10000,
    0,
    20,
    0,
    50,
    200,
    60,
    120,
    100000,
    0.8,
    0.95,
    true,
    true,
    true,
    '',
    '',
    '',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '1 month',
    true,
    true,
    CURRENT_TIMESTAMP,
    false
);
